dist: xenial
language: go
go:
    - master

# before_install
# install - install any dependencies required
install:
    #- go get github.com/gohugoio/hugo    # consume time 70.85s
    - mkdir $HOME/hugo-src
    - pushd $HOME/hugo-src
    - git clone https://github.com/gohugoio/hugo.git
    - pushd hugo
    - go install

before_script:
    - popd
    - popd
    - ls -la
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo

deploy:
  provider: pages
  local-dir: public
  repo: red-jackets-jazzband/red-jackets-jazzband.github.io
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  keep-history: true
  on:
    branch: master
