dist: xenial
language: go
os: linux
go:
    - "1.19"

# before_install
# install - install any dependencies required
install:
    #- go get github.com/gohugoio/hugo    # consume time 70.85s
    - mkdir $HOME/hugo-src
    - pushd $HOME/hugo-src
    - git clone --branch v0.83.1 https://github.com/gohugoio/hugo.git
    - pushd hugo
    - go install

before_script:
    - popd
    - popd
    - ls -la
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo

deploy:
  provider: pages
  strategy: git
  local_dir: public
  repo: red-jackets-jazzband/red-jackets-jazzband.github.io
  target_branch: master
  skip_cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer_from_gh: true
  keep_history: true
  on:
    branch: master
