baseURL = "https://www.redjackets.nl/"
languageCode = "en-us"
title = "Red Jackets Jazzband"
theme = "split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS"]
timeout = 60000

DefaultContentLanguage = "en"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-37632234-2"

# Copyright
copyright = "&copy;2019 Red Jackets Jazzband"

[languages]
  [languages.en]
    weight = 1
  [languages.nl]
    weight = 2
  [languages.de]
    weight = 3

[params]

  custom_css = "assets/css/split.css"

  # Metadata for search engines and social sharing
  author = "Red Jackets Jazzband"
  description = "Red Jackets jazzband a true jazz orchestra"
  shareImage = "images/redjackets_logo_small.png"
  twitterHandle = "redjacketsjazz"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/quedlinburg_back_name.jpg"
      position = "center top"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      # file = "videos/background.mp4"
      youtubeId = "q2kOF8ef24A"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:info@redjackets.nl"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/RedJacketsJazz"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/redjacketsjazzband/"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/RedJacketsJazzband"

      [[params.links.list2.link]]
        text = "Youtube"
        url = "https://www.youtube.com/channel/UCH9Ci0xgnyhUaZ8gXQdaiLQ"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Pages"

      [[params.links.list3.link]]
        text = "Agenda"
        url = "/agenda"

      [[params.links.list3.link]]
        text = "Band"
        url = "band"

      [[params.links.list3.link]]
        text = "In Action"
        url = "/in-action"

      [[params.links.list3.link]]
        text = "Songs"
        url = "/songs"

      [[params.links.list3.link]]
        text = "Songbook"
        url = "/songbook"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

# Below settings should fix any GDPR concerns according to Hugo docs
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = true
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
