# This is a generated file by dfetch. Don't edit this, but edit the manifest.
# For more info see https://dfetch.rtfd.io/en/latest/getting_started.html
dfetch:
  branch: master
  hash: 015824dd54c5a22580989efcd07a9347
  last_fetch: 02/06/2026, 21:42:17
  patch: patches/themes-split.patch
  remote_url: https://github.com/escalate/hugo-split-theme.git
  revision: fabd3dd8c3a3f27c398ff6451fe9adbc3323518d
  tag: ''
