name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - uses: lowply/build-hugo@v0.150.1

      - name: Publish
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: public
          repo: red-jackets-jazzband/red-jackets-jazzband.github.io
          branch: master
          token: ${{ secrets.GH_RJ_DEPLOY }}
