name: Publish

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: lowply/build-hugo@v0.152.2

      - name: Check for broken links
        run: |
          pip install linkchecker
          linkchecker public/index.html

      - uses: actions/upload-artifact@v5.0.0
        with:
          name: website
          path: public/

  publish:
    runs-on: ubuntu-latest
    needs:
    - build
    permissions:
      id-token: write
    steps:
      - name: Download the website
        uses: actions/download-artifact@v5.0.0
        with:
          name: website
          path: public/
      - name: Publish
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        if: github.ref == 'refs/heads/master'
        with:
          dir: public
          repo: red-jackets-jazzband/red-jackets-jazzband.github.io
          branch: master
          token: ${{ secrets.GH_RJ_DEPLOY }}
